
name: Deploy to GitHub-Pages
on:
   pull_request:
     branches:
       - main
   push:
     branches:
       - main
jobs:
   deploy:
     name: Deploy
     runs-on: ubuntu-latest
     steps:
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
           node-version: 16.x
       - name: Checkout
         uses: actions/checkout@v3
         with:
           persist-credentials: false
       - name: Install dependencies
         run: npm ci
       # - name: Install dependencies
       #   run: npm install gh-pages --save-dev
    #    - name: Run checks
    #      run: npm run lint
       - name: Build project
         run: npm run build

       - name: Download artifact
         id: download-artifact
         uses: dawidd6/action-download-artifact@v2
         with:
           name: production-files
           repo: https://github.com/Alienatedem/test-repository
           # workflow: {the other workflow filename e.g. build.yml}
           path: https://github.com/Alienatedem/test-repository/tree/gh-pages
           search_artifacts: true
       # - name: same test
       #   run: npm run build
    #    - name: Deploy
        #  uses: JamesIves/github-pages-deploy-action@v4
        #  with:
        #    token: ${{ secrets.GITHUB_TOKEN }}
        #    folder: /build/
        #    branch: main
        #    single-commit: true
